export enum ENUM_PERMISSION_SUBJECT {
  HOME = 'HOME',
}

export enum ENUM_PERMISSION {
  HOME_VIEW = 'HOME.VIEW',
  HOME_CREATE = 'HOME.CREATE',
  HOME_UPDATE = 'HOME.UPDATE',
  HOME_DELETE = 'HOME.DELETE',
}