export enum ENUM_PERMISSION_SUBJECT {
  HOME = "HOME",
  STAFF = "STAFF",
  USER = "USER",
  GROUP_ROLE = "GROUP_ROLE",
  ROLE = "ROLE",
  CATEGORY = "CATEGORY",
}

export enum ENUM_PERMISSION {
  HOME_VIEW = "HOME.VIEW",
  HOME_CREATE = "HOME.CREATE",
  HOME_UPDATE = "HOME.UPDATE",
  HOME_DELETE = "HOME.DELETE",

  // STAFF
  STAFF_VIEW = "STAFF.VIEW",
  STAFF_CREATE = "STAFF.CREATE",
  STAFF_UPDATE = "STAFF.UPDATE",
  STAFF_DELETE = "STAFF.DELETE",

  // User
  USER_VIEW = "USER.VIEW",
  USER_CREATE = "USER.CREATE",
  USER_UPDATE = "USER.UPDATE",
  USER_DELETE = "USER.DELETE",

  // Group Role
  GROUP_ROLE_VIEW = "GROUP_ROLE.VIEW",
  GROUP_ROLE_CREATE = "GROUP_ROLE.CREATE",
  GROUP_ROLE_UPDATE = "GROUP_ROLE.UPDATE",
  GROUP_ROLE_DELETE = "GROUP_ROLE.DELETE",

  // Role
  ROLE_VIEW = "ROLE.VIEW",
  ROLE_CREATE = "ROLE.CREATE",
  ROLE_UPDATE = "ROLE.UPDATE",
  ROLE_DELETE = "ROLE.DELETE",

  // Category
  CATEGORY_VIEW = "CATEGORY.VIEW",
  CATEGORY_CREATE = "CATEGORY.CREATE",
  CATEGORY_UPDATE = "CATEGORY.UPDATE",
  CATEGORY_DELETE = "CATEGORY.DELETE",
}
